package com.gzc.infrastructure.dao.po;

// Code generated by https://gotool.top

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class SeckillVoucher {

    private Long voucherId;

    private Integer	stock;

    private Date createTime;

    private Date beginTime;

    private Date	endTime;

    private Date	updateTime;

}